# Generated by Django 4.0.2 on 2022-03-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.session'),
        ),
        migrations.DeleteModel(
            name='Session_Year',
        ),
    ]
