# Generated by Django 4.0.2 on 2022-02-15 08:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_user_type_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.session_year'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_mobile_no',
            field=phone_field.models.PhoneField(default=django.utils.timezone.now, max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_optional_mobile_no',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (1, 'HOD'), (3, 'STUDENT')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.course'),
        ),
    ]
