# Generated by Django 4.0.2 on 2022-02-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_staffnotification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='message_status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (1, 'HOD'), (3, 'STUDENT')], default=1, max_length=50),
        ),
    ]
