# Generated by Django 4.0.2 on 2022-02-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_student_address_student_permanent_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (3, 'STUDENT'), (1, 'HOD')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_mobile_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_optional_mobile_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
